export * from './AboutUs';
export * from './LandingPage';
export * from './PrivacyPolicy';
export * from './Login';
export * from './Contratar'
export * from './ContactUs'
export * from './Oportunidades'
export * from './Register';
export * from './shared/Footer';
export * from './shared/Navbar';